development:
  sessions:
    default:
      database: gdetails_development
      hosts:
        - localhost:27017
production:
 sessions:
   default:
     database: gdetails_production
     hosts:
       - 176.58.109.95:27017  		